config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms

  root to: 'application#redirect_home'

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, length: { maximum: 200 }
  validates :body, length: { maximum: 20000 }

  def updated_at_count
    self.updated_at.to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rooms

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def redirect_home
    redirect_to rooms_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = accessible_rooms.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def accessible_rooms
      Room.where(user: current_user)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = accessible_rooms.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en"){"ng-app" => "Kanna"}
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Kanna"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Kanna
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Room list", rooms_path
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to "Logout", destroy_user_session_path, method: :delete

    .container
      .row
        .col-lg-9.spacer
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            = yield :sidebar
    %footer.footer
      .container
        %ul.nav.navbar-nav.navbar-bottom
          %p.navbar-text &copy; lni_T 2015

app/views/rooms/_form.html.haml
= form_for @room, html: { class: "form room" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@room[:name])
  .form-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_area :body, rows: 15, :class => 'form-control'
    = error_span(@room[:body])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), rooms_path, :class => 'btn btn-default'

- content_for :sidebar do
  %h3 Control
  %ul.nav.nav-list
    %li= link_to t('.new', :default => t("helpers.links.new")), new_room_path

app/views/rooms/edit.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rooms/index.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @rooms.each do |room|
      %tr
        %td= link_to room.id, room_path(room)
        %td= room.name
        %td=l room.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), room_path(room), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), room_path(room), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- content_for :sidebar do
  %h3 Control
  %ul.nav.nav-list
    %li= link_to t('.new', :default => t("helpers.links.new")), new_room_path

app/views/rooms/new.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rooms/show.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%div{'ng-controller' => 'RoomsController'}
  %alert{'ng-repeat' => 'error in room.errors', :type => 'danger'}
    {{error}}
  %form.room{'ng-submit' => 'update()'}
    .form-group
      %label.control-label Name
      .controls
        = text_field_tag 'room[name]', '', 'ng-model' => 'room.name', :class => 'form-control'
    .form-group
      %label.control-label Body
      .controls
        = text_area_tag 'room[body]', '', rows: 15, 'ng-model' => 'room.body', :class => 'form-control'
    = submit_tag 'save', class: 'btn btn-primary'
    = link_to t('.back', :default => t("helpers.links.back")), rooms_path, :class => 'btn btn-default'

- content_for :sidebar do
  %h3 Control
  %ul.nav.nav-list
    %li= link_to t('.new', :default => t("helpers.links.new")), new_room_path
    %hr
    %li= link_to t('.destroy', :default => t("helpers.links.destroy")), room_path(@room), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'